### ISSUE TITLE
Let the label colormap be specified in the configuration file

### ISSUE THREAD

**Issue by ithron** [ithron/CortidQCT#16]
Currently the color to label map is hard coded as ColorToLabelMaps::default. In future there shouldbe an option in the configuration file to specify which colormap to use.
Something like this:
```yaml
referenceMesh:
  mesh: myMesh.off
  colorToLabelMap: 
    type: custom
    map:
      - [[255, 0, 0], 0]
      - [[0, 255, 0], 1]
```
