### ISSUE TITLE
Mesh sometimes vanishes after a few dozen iterations

### ISSUE THREAD

**Issue by ithron** [ithron/CortidQCT#48]
**Describe the bug**
Sometimes the mesh seems to vanish after a few dozen iterations (most of the cases > 60).
In those cases the Mesh collapses into a single point.
In other cases the mesh just moves (far) outside of volume bounds.
This happens within a single iteration, so the mesh moves / scales abruptly.
There is also not much visible change in the iterations before.

**To Reproduce**
Not easy to reproduce without an example volume (which cannot be made public).
Also depends on configuration and volume.
```yaml
---

# Paths are relative the current file
referenceMesh:
  mesh:   ../ReferenceMeshes/Vertebra.off
  colorToLabelMap:
    type: custom
    map:
      - [[255, 0, 0], 1]
      - [[0, 255, 0], 0]
      - [[0, 0, 255], 3]
      - [[255, 255, 0], 2]
    undefinedLabel: 4
  origin:
    type: relative
    xyz: [0.5, 0.5, 0.5]
  scale: 1
  rotation: [-10, 0, 0]

measurementModel: ../Models/SomeModel.yml

sigmaE: 5.4
sigmaS: 1.0

maxIterations: 120
minNonDecreasing: 3
decay: 0.1
```

**Screenshots**
![cortidqct-bug](https://user-images.githubusercontent.com/203141/52554790-3799ce00-2de8-11e9-8eb1-f808bb0b0082.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19 Tara x86_64
 - Version: MATLAB Toolbox version 1.2.2.3 on MATLAB 2018b
